* Numpy: 다차원 배열 데이터
    * 정해진 길이, 정해진 타입, 정수 인덱스
    * 벡터화 연산(배열 원소 더하기 등)<-> 리스트 연결, 복사...
    * 특정한 배열에 속한 원소들에 대해서 반복적 연산
    * 불러언 인덱스 배열 -> 필터링
* Pandas: 2차원 배열, 행렬 형태의 딕셔너리 같이 키를 가진 데이터(행과 열 모두 인덱스)
    * 엑셀, 표 형태의 일반적으로 볼 수 있는 데이터
    * 값들은 배열이다.(열단위의) -> numpy.ndarray
    * 값마다 인덱스가 배정 되어있고 반드시 정수일 필요가 없다
        * 특정한 값을 붙여주는데 `라벨`이라고 부르며 문자열, 졍수, 시간, 날짜 등
            => 인덱서, 인덱싱등 가능하며 호출할 수 있다.
    * `라벨` -> 딕셔너리와 유사함. 키를 통해서 데이터 묶음에 특정한 데이터를 CRUD(생성,읽기,수정,삭제)

## Pands와 Numpy
데이터 분석, 특성을 확인하기 위한 작없을 하려면 Pands: 인간이 보기 좋음 (이해, 분석)<br>
모델링, 프로그램같이 컴퓨터가 작업을 해주기 위한 형태로 변형하려면 Numpy: 속도가 빠르고, 컴퓨터가 효율적으로 변형, 분석 등을 할 수 있다

## 시리즈(Series)
Serial/Serials -> 연속되어 있음
-> 배열(array), 리스트(List)
* 이름: 원소들마다 부르는 이름이 있다.
* 정수를 인덱스로 쓰거나 키로 값을 부를 수 있다.

pd.Series(...) # 연속된 데이터 묶음<br>
리스트, 배열...<br>
index : 연속된 데이터 묶음 -> 시리즈 내의 데이터와 매칭이 되는 나열된 이름들
index를 넣지 않으면 range,arrang 같이 해당 길이에 맞는 정수 인덱스가 자동으로 부여됨

In [21]:
import pandas as pd # pd
import numpy as np

In [2]:
s = pd.Series([9904312, 3448737, 2890451, 2466052], 
              # 연속된 데이터 묶음 (리스트, 튜플, 1차원 배열...)
              index=["서울", "부산", "인천", "대구"]
              # 넣어준 데이터의 길이와 일치하는 인덱스 묶음
              # 순서대로 짝지어서 데이터가 들어가게 됨
              # 인덱스를 안 넣어주면 range 비슷하게 생성 (길이에 맞춰서)
              )
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

#### `s.index` : 시리즈의 인덱스(라벨링 된 이름)
#### `s.values` : 시리즈의 값(배열) -> 같은 타입

In [3]:
s.index, type(s.index)

(Index(['서울', '부산', '인천', '대구'], dtype='object'),
 pandas.core.indexes.base.Index)

In [4]:
s.values, type(s.values) # numpy.ndarray

(array([9904312, 3448737, 2890451, 2466052], dtype=int64), numpy.ndarray)

#### s.name, s.index.name : 시리즈 이름, 시리즈의 인덱스에 이름을 붙일 수 있다.


## 시리즈 연산
* Numpy 배열과 유사 -> 벡터화 연산
* 연산 자체는 '값'(배열) -> 인덱스(라벨)은 연산 불가!

## 시리즈 인덱싱 & 슬라이싱
* 시리즈는 배열, 딕셔너리와 유사함
* Numpy 배열에서 전부 사용가능한 인덱스 방법(정수 인덱싱, 배열인덱싱) 전부 사용가능
* 인덱스 라벨을 이용한인덱싱 -> 딕셔너리처럼 키로 호출
* 인덱싱 가능 -> 슬라이싱 가능
* 예제 - 서울, 부산 등 라벨 호출, 0,1,2,.. 처럼 정수 호출도 가능하다

In [6]:
s[3], s['대구']

(2466052, 2466052)

In [8]:
s[[0, 3, 1]] # 순서를 바꿔서 정수 인덱스로 부르기

서울    9904312
대구    2466052
부산    3448737
dtype: int64

In [9]:
s[["서울", "대구", "부산"]] # 순서를 바꿔서 라벨로 부르기

서울    9904312
대구    2466052
부산    3448737
dtype: int64

* 벡터화 연산이 가능 = 모든 데이터에 대한 특정 조건 만족여부를 (True/Fale)로 표현 가능
* == , >,<, 등 연산의 결과를 불리언 배열로 만들어서 불리언 배열 인덱싱을 통해 시리즈에도 사용 가능

In [10]:
# 인구가 250만 초과, 500만 미만
s[(s > 250e4) & (s < 500e4)] # e='0의 개수'

부산    3448737
인천    2890451
dtype: int64

## 슬라이싱
* 라벨 슬라이싱: ["a":"b"]처럼 범위를 지정했을때 라벨을 통한 슬라이싱에서는 a에서 b까지 포함된다.
* 판다스 - 라벨을 통해서 해당 데이터를 속성처럼 호출
`series.속성명` -> 해당 라벨을 호출해서 사용할 수 있다.

In [11]:
s['부산':'대구'] # 1, 2, 3

부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [12]:
# 몇몇 특수문자나 예약어를 건들이지 않으면 문자열로 .을 통해 속성마냥 인덱스 값에 접근
s.부산, s.대구, s['부산'], s['대구']

(3448737, 2466052, 3448737, 2466052)

* 변수명으로 지정할 수 있는 일반적인 (공백없는) 단어들로 구성된 라벨은 시리즈에 .을 통해서 속성으로 호출

## 인덱스 기반(시리즈 간) 연산
* 시리즈는 vaule에 한해서 벡터화 연산 할 수 있음
* 시리즈들간에도 벡터화 연산을 할 수 있음
* 인덱스 라벨이 일치하는 값들에 한해서 시리즈 간 연산
* 라벨이 일치 하지 않는다(한쪽 라벨이 비어있다.) -> NaN

In [14]:
s2 = pd.Series({
    "서울": 9631482,
    "부산": 3393191,
    "인천": 2632035,
    "대전": 1490158
    }) # 딕셔너리 내부에는 순서 X, 시리즈->순서 보장 
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [15]:
ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

Nan == Null : series.notnull() → 불리언 배열 값 → 인덱싱 → 비어 있지 않은 값들

In [16]:
ds.notnull() # null인 데이터들은 False, not null인 데이터들은 True -> 불리언 배열

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [18]:
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

### 시리즈의 데이터 갱신, 추가, 삭제

- 딕셔너리 처럼 인덱싱해서 갱신, 추가, 삭제가 가능하다.
     * 새로운 키 값을 주면 해당 키 값에 대해서 새로운 값을 할당, 
     * 기존에 존재하던 키를 호출한 다음에 수정. 
     * `del` 로 지워주면 됨
- 배열처럼 → 인덱싱해서 → 새롭게 키를 만들어서 처리 X → 배열이니까 # 무슨말? 

## 데이터프레임 (DataFrame)

- 시리즈 : 1차원 배열 데이터 + 행방향 인덱스
- 데이터프레임 : 2차원 배열 데이터 + 행방향 인덱스 & 열방향 인덱스
행방향 인덱스와 열방향 인덱스를 통해 연산을 할 수 있음

### 데이터프레임 생성
* 하나의 열이 될 수 있는 데이터 묶음(리스트, 일차원)
    + 원하는 만큼의 구성할 열들(각 열마다 다른 데이터타입이 들어갈 수 있다.)
* 열의 이름을 키로 기자는 딕셔너리처럼,
    키: 연속된 데이터(생성된 타입이 다 동일해야함)
- 이 데이터를 `pd.DataFrame(...)`에 넣어서 처리
    - 열 방향 인덱스를 넣어주고 싶다 : `pd.DataFrame(columns=...)`
    - 행 방향 인덱스를 넣어주고 싶다 :
    `pd.DataFrame(index=…)`

In [19]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

* df.values # 데이터 (배열)
* df.columns # 열 이름들, 컬럼들 (열방향 인덱스)
* df.index # 행 이름들, 행방향 인덱스
* df.T # 데이터 프레임을 전치(행을 열로, 열을 행으로)

In [23]:
arr = np.arange(10).reshape(5, 2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### 전치 이해하기
[(0,0),(0,1)]<br><br>
[(1.0),(1,1)]<br><br>
<hr>
0,0 => 0,0<br>
0,1 => 1,0<br>
1,0 => 0,1<br>
1,1 => 1,1<br>

In [24]:
arr.T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

df[열이름] = 새로운 데이터들 넣을 수 있음

In [25]:
df['2010-2015 증가율'] = df['2010-2015 증가율'] * 100
df # 2010-2015 증가율 키,이름,라벨을 가진 열을 수정(갱신)

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

### 열 인덱싱 - 정수 값을 넣으면 오류!
* 인덱스로 열이름을 넣으면 열의 값이 나온다!
* df[열라벨]을 하면 시리즈 형태로 나온다(하나의 열을 전부 보여주는 경우)
* df.shape는 (행길이, 열길이) -> 행의 길이
* 정수형 인덱스 -> 딕셔너리 키 X -> 에러가 난다
* 정수형 인덱스 = 열 라벨의 이름 / 위치? -> 정수형 인덱스
* Key Error

### 행 인덱싱 - 
* 범위로 (:) <- 슬라이싱을 한다
* df[0:1]# 정수형을 넣게되면 -> 끝점을 제외하고 범위 -> 데이터프레임
* df[0:1]
* df['서울':'대전']
* 문자열을 넣게되면? -> 라벨 인덱싱 -> 끝점 포함

### 개별 데이터 인덱싱
df['열이름'] # 시리즈 형태로 출력
df['열이름']['행이름'] # 개별값

### 데이터 입출력
* 데이터를 Pandas에 넣으면 표 형태의 데이터로 나옴
* csv - excel 유사해보이는데, 엑셀 -> 서식(꾸며주는 폰트, 포맷...)
* excel -> 속도가 느리고 용량이 커요
* csv -> 핵심만 남겨서 데이터 자체와, 데이터를 구분해주는 데이터 자체와 데이터를 구분해주는 ,(comma)
* comma seperated value 
* read_xxx / to_xxx
* pd.read_csv(...) # 경로, URL
* pd.to_csv(...)
* pd.read_excel(...) / pd.to_excel(...)

df # 읽어와서 무엇부터 볼 것인가?
* 데이터의 특성을 보기 위해서 상단 5개? 하단 5개?
* df.head()
* df.tail()

## 데이터프레임 고급인덱싱(`loc`,`iloc`)
* 인덱싱은 특정한 데이터를 고르는 것
* 기준 - 라벨 인덱스, 배열 - 정수 인덱스
* 기본 인덱싱(`[ ]`): 열(라벨, 라벨리스트), 행(`:`라벨 범위)
* Numpy에서 행렬기반으로 인덱싱 <-> Pandas 기본 인덱싱이 매칭이 안됨
* (행, 열) → 인덱싱해주고 싶음때 `loc` `iloc`를 사용한다.
    * `loc` : 라벨 인덱스 (딕셔너리 키)
    * `iloc` : 정수 인덱스 (리스트, 배열에서의 나열된 원소의 위치)
* 일반적인 메소드처럼 () 소괄호를 쓰지 X → [] 대괄호를 쓰기 때문에 인덱서(indexer)
df.loc[행 인덱싱 값] - 행만 넣어주거나
df.loc[행 인덱싱 값, 열 인덱싱 값] - 행, 열을 순서대로 넣고 싶을때
* <정수>, 문자열 인덱스 - 

* df.loc[행 인덱싱 값] # 행만 넣어주거나
* df.loc[행 인덱싱 값, 열 인덱싱 값]
* 행, 열을 순서대로 넣어주거나
* <정수>, 문자열 인덱스 # range, arange
* 인덱스 데이터 / df.loc['서울'] df.loc[0] <- 행
* 인덱스 데이터 슬라이스
* df.loc['서울':'부산'] df.loc[0:1] (라벨)
* df.loc <- 불리언 배열 인덱싱 (필터링)
* df.loc[행] <- df.loc[열...?] # KeyError!!!
* df.loc[:,열]
* 슬라이싱 -> : (아무것도 안붙은 콜론 : all)
* df.loc -> 열만 뽑고 싶다
* df.loc[:,열 정보값] = df[열 정보값]

* <p style="color:red">정수 인덱싱은 끝값 -1</p>
* <p style="color:red">라벨 인덱싱은 끝값까지 포함</p>

* iloc -> 라벨이 아니라 순서를 나타내는 integer 인덱스 I
* loc도 정수를 사용할 순 있음 -> 부여된 정수
* loc 정수를 사용할 수 있다 -> 0번자리인데 => 100을 넣을 수있다 = 키값 처럼 익히기
* 절대적인 좌표는 변하지는 않지만 부르는 이름은 달라질 수 있음
* df.iloc[행 순서 정수 인덱스]
* df.iloc[행 순서 정수 인덱스, 열 순서 정수 인덱스]
* 슬라이스는 작동하고 -> 슬라이스 넣었을 때 끝 포함 X

## loc와 iloc의 차이
* loc는 조건을 넣어서 필터링 할 수 있음
* iloc는 배열인덱싱을 할 수 없다.